import os
import pandas as pd
import streamlit as st

# -----------------------------------------------------------------------------
# 1. PAGE SETUP & THEME CONFIGURATION
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Stock Scanner",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# Custom dark navy theme matching your original scanner
st.markdown(
    """
<style>
    .stApp {
        background-color: #0b1426;
        color: #e2e8f0;
    }
    .custom-table-container {
        width: 100%;
        overflow-x: auto;
        border: 1px solid #1e293b;
        border-radius: 8px;
        background-color: #0d192d;
    }
    .scanner-table {
        width: 100%;
        border-collapse: collapse;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        font-size: 13px;
        text-align: center;
    }
    .scanner-table th {
        background-color: #112240;
        color: #38bdf8;
        font-weight: 700;
        padding: 12px 10px;
        border: 1px solid #1e293b;
        white-space: nowrap;
        font-size: 12px;
        text-transform: uppercase;
    }
    .scanner-table td {
        padding: 10px 8px;
        border: 1px solid #1e293b;
        vertical-align: middle;
        background-color: #0b1426;
    }
    .scanner-table tr:hover td {
        background-color: #132238;
    }
    .badge {
        display: inline-block;
        padding: 2px 10px;
        border-radius: 12px;
        font-size: 10px;
        font-weight: 700;
        text-transform: uppercase;
        margin-top: 4px;
    }
    .badge-green {
        background-color: rgba(16, 185, 129, 0.15);
        color: #34d399;
        border: 1px solid #059669;
    }
    .badge-purple {
        background-color: rgba(168, 85, 247, 0.15);
        color: #c084fc;
        border: 1px solid #7e22ce;
    }
    .badge-red {
        background-color: rgba(239, 68, 68, 0.15);
        color: #fca5a5;
        border: 1px solid #dc2626;
    }
    .cell-value {
        font-weight: 600;
        color: #f8fafc;
        font-size: 13px;
    }
    .stock-name {
        color: #38bdf8;
        font-weight: 700;
    }
</style>
""",
    unsafe_allow_html=True,
)


# -----------------------------------------------------------------------------
# 2. UNIVERSAL CELL BADGE FORMATTER
# -----------------------------------------------------------------------------
def format_cell_to_badge(cell_value):
    """Cleans raw string clutter and converts second lines into styled pill badges."""
    if pd.isna(cell_value):
        return ""

    cleaned = (
        str(cell_value)
        .replace("\\n", "\n")
        .replace("\r", "")
        .strip()
    )
    lines = [line.strip() for line in cleaned.split("\n") if line.strip()]

    if not lines:
        return ""

    value_part = lines[0]
    badge_part = lines[1] if len(lines) > 1 else ""

    badge_html = ""
    if badge_part:
        b_upper = badge_part.upper()
        if any(
            k in b_upper
            for k in [
                "STRONG BUY",
                "SPIKE",
            ]
        ):
            badge_class = "badge-purple"
        elif any(
            k in b_upper
            for k in [
                "BUY",
                "BULLISH",
                "UP",
                "STRONG",
                "YES",
            ]
        ):
            badge_class = "badge-green"
        elif any(
            k in b_upper
            for k in [
                "WEAK",
                "LOW VOL",
                "BEARISH",
                "NO",
            ]
        ):
            badge_class = "badge-red"
        else:
            badge_class = "badge-green"

        badge_html = f'<br><span class="badge {badge_class}">{badge_part}</span>'

    return f'<div class="cell-value">{value_part}</div>{badge_html}'


# -----------------------------------------------------------------------------
# 3. DYNAMIC DATA LOADER
# -----------------------------------------------------------------------------
def load_all_stocks():
    # If you have a local CSV file generated by your scanner script:
    csv_filename = "stocks.csv"  # Update to your actual CSV filename if needed
    if os.path.exists(csv_filename):
        return pd.read_csv(csv_filename)

    return None


df = load_all_stocks()

# Interactive file uploader fallback if local CSV isn't found
if df is None:
    uploaded_file = st.file_uploader(
        "Upload your full stock list CSV file", type=["csv"]
    )
    if uploaded_file is not None:
        df = pd.read_csv(uploaded_file)

# -----------------------------------------------------------------------------
# 4. RENDER COMPLETE UNFILTERED TABLE
# -----------------------------------------------------------------------------
if df is not None:
    columns = list(df.columns)

    html_table = (
        '<div class="custom-table-container"><table'
        ' class="scanner-table"><thead><tr>'
    )
    for col in columns:
        html_table += f"<th>{col}</th>"
    html_table += "</tr></thead><tbody>"

    # Iterates through ALL stocks in your list without any filtering
    for idx, row in df.iterrows():
        html_table += "<tr>"
        for col in columns:
            val = row[col]
            col_str = str(col).upper().strip()

            if col_str in ["#", "SR", "S.NO"]:
                html_table += (
                    f'<td style="color: #64748b; font-weight: bold;">{val}</td>'
                )
            elif "NAME" in col_str or "STOCK" in col_str:
                html_table += f'<td class="stock-name">{val}</td>'
            else:
                formatted_content = format_cell_to_badge(val)
                html_table += f"<td>{formatted_content}</td>"
        html_table += "</tr>"

    html_table += "</tbody></table></div>"

    st.markdown(html_table, unsafe_allow_html=True)
